<a href="https://colab.research.google.com/github/shivansh0901/classification-models-on-Iris-dataset/blob/main/iris_ann_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Artificial Neural Network

### Importing the libraries

In [ ]:
import numpy as np
import pandas as pd
import tensorflow as tf

### Importing the dataset

In [ ]:
dataset=pd.read_csv("iris.csv")
x=dataset.iloc[:,:-1].values
y=dataset.iloc[:,-1].values

In [ ]:
print(x)

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.1 1.5 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.

### Encoding categorical data

In [ ]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0])], remainder='passthrough')
y = np.array(ct.fit_transform(y.reshape(len(y),-1)))

In [ ]:
print(y)

[[1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0.

### Feature Scaling

In [ ]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(x)
X_test = sc.transform(x)

## Part 2 - Building the ANN

In [ ]:
ann=tf.keras.Sequential()
ann.add(tf.keras.layers.Dense(units=16 ,activation='relu'))
ann.add(tf.keras.layers.Dense(units=16 ,activation='relu'))

In [ ]:
ann.add(tf.keras.layers.Dense(units=3 ,activation='softmax'))

## Part 3 - Training the ANN

### Compiling the ANN

In [ ]:
ann.compile(optimizer='adam',loss='categorical_crossentropy',metrics=['accuracy'])

### Training the ANN on the Training set

In [ ]:
ann.fit(x,y ,batch_size=20,epochs=100)

Epoch 1/100
8/8 [==============================] - 2s 7ms/step - loss: 1.1540 - accuracy: 0.3467
Epoch 2/100
8/8 [==============================] - 0s 10ms/step - loss: 1.0377 - accuracy: 0.6133
Epoch 3/100
8/8 [==============================] - 0s 14ms/step - loss: 0.9823 - accuracy: 0.5867
Epoch 4/100
8/8 [==============================] - 0s 7ms/step - loss: 0.9443 - accuracy: 0.6400
Epoch 5/100
8/8 [==============================] - 0s 7ms/step - loss: 0.9008 - accuracy: 0.6600
Epoch 6/100
8/8 [==============================] - 0s 7ms/step - loss: 0.8621 - accuracy: 0.6600
Epoch 7/100
8/8 [==============================] - 0s 10ms/step - loss: 0.8253 - accuracy: 0.6667
Epoch 8/100
8/8 [==============================] - 0s 5ms/step - loss: 0.7878 - accuracy: 0.6667
Epoch 9/100
8/8 [==============================] - 0s 5ms/step - loss: 0.7559 - accuracy: 0.6667
Epoch 10/100
8/8 [==============================] - 0s 5ms/step - loss: 0.7146 - accuracy: 0.6800
Epoch 11/100
8/8 [========

### Predicting the Test set results

In [ ]:
y_pred = ann.predict(x)

5/5 [==============================] - 0s 6ms/step


In [ ]:
print(y_pred)

[[9.95738506e-01 4.24633082e-03 1.51939375e-05]
 [9.90966916e-01 8.98419507e-03 4.87781872e-05]
 [9.93719697e-01 6.24881033e-03 3.15338621e-05]
 [9.92440403e-01 7.52115529e-03 3.83379556e-05]
 [9.95628893e-01 4.35606437e-03 1.49635780e-05]
 [9.96977806e-01 3.01523809e-03 7.03213982e-06]
 [9.93981063e-01 5.99231478e-03 2.65068265e-05]
 [9.95023906e-01 4.95744124e-03 1.86757006e-05]
 [9.90070760e-01 9.86593217e-03 6.34272728e-05]
 [9.92943108e-01 7.02404557e-03 3.28394490e-05]
 [9.96716738e-01 3.27408663e-03 9.11782445e-06]
 [9.94041145e-01 5.93625661e-03 2.26036718e-05]
 [9.91990209e-01 7.96702318e-03 4.27275481e-05]
 [9.91267264e-01 8.67383555e-03 5.90119162e-05]
 [9.98018503e-01 1.97668816e-03 4.60953379e-06]
 [9.98246610e-01 1.75034651e-03 2.93312269e-06]
 [9.97206986e-01 2.78522819e-03 7.69622238e-06]
 [9.95343268e-01 4.63958597e-03 1.70926614e-05]
 [9.96690691e-01 3.30160116e-03 7.62244645e-06]
 [9.96316016e-01 3.67340911e-03 1.05180106e-05]
 [9.94592428e-01 5.39013837e-03 1.730994

In [ ]:
ypred1=np.array(y_pred[:,0])
ypred1=ypred1.flatten()
ypred2=np.array(y_pred[:,1])
ypred2=ypred2.flatten()
ypred3=np.array(y_pred[:,2])
ypred3=ypred3.flatten()
print(ypred3)

[1.51939375e-05 4.87781872e-05 3.15338621e-05 3.83379556e-05
 1.49635780e-05 7.03213982e-06 2.65068265e-05 1.86757006e-05
 6.34272728e-05 3.28394490e-05 9.11782445e-06 2.26036718e-05
 4.27275481e-05 5.90119162e-05 4.60953379e-06 2.93312269e-06
 7.69622238e-06 1.70926614e-05 7.62244645e-06 1.05180106e-05
 1.73099470e-05 1.19827992e-05 2.20117690e-05 3.82868711e-05
 3.00572410e-05 4.63551041e-05 2.38706725e-05 1.44702090e-05
 1.87304886e-05 3.10599062e-05 3.70645612e-05 2.38814646e-05
 7.32359149e-06 4.75300294e-06 3.28394490e-05 3.17234917e-05
 1.48903564e-05 3.28394490e-05 5.17844346e-05 1.84133860e-05
 1.75799851e-05 3.00193758e-04 4.14770548e-05 2.48769593e-05
 1.21582461e-05 5.63044450e-05 1.08719987e-05 3.42291205e-05
 1.00358393e-05 2.39644578e-05 2.53970083e-02 5.80317602e-02
 8.55342224e-02 1.48115575e-01 1.02017716e-01 2.81300664e-01
 1.49105340e-01 3.48898731e-02 5.38450629e-02 1.53077424e-01
 7.12898672e-02 7.80667365e-02 3.48300636e-02 2.48266220e-01
 2.51059476e-02 2.145887

In [ ]:
yfinal=[]
for i in range(0,len(ypred1)):
  if(ypred1[i]>ypred2[i] and ypred1[i]>ypred3[i]):
    yfinal.append("Iris-setosa")
  elif(ypred2[i]>ypred1[i] and ypred2[i]>ypred3[i]):
    yfinal.append("Iris-versicolor")
  elif(ypred3[i]>ypred1[i] and ypred3[i]>ypred2[i]):
    yfinal.append("Iris-virginica")
yfinal=np.array(yfinal)
print(yfinal)

['Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa'
 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa'
 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa'
 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa'
 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa'
 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa'
 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa'
 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa'
 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa'
 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa'
 'Iris-versicolor' 'Iris-versicolor' 'Iris-versicolor' 'Iris-versicolor'
 'Iris-versicolor' 'Iris-versicolor' 'Iris-versicolor' 'Iris-versicolor'
 'Iris-versicolor' 'Iris-versicolor' 'Iris-versicolor' 'Iris-versicolor'
 'Iris-versicolor' 'Iris-versicolor' 'Iris-versicolor' 'Iris-versicolor

### Making the Confusion Matrix

In [ ]:
from sklearn.metrics import confusion_matrix,accuracy_score
yoriginal=dataset.iloc[:,-1].values
cm=confusion_matrix(yoriginal,yfinal)
print(cm)
accuracy_score(yoriginal,yfinal)

[[50  0  0]
 [ 0 48  2]
 [ 0  2 48]]


0.9733333333333334